#ifndef PROJECT_VERSION_H
#define PROJECT_VERSION_H

#define PROJECT_NAME "mantidsTLSClient"
#define PROJECT_VER  "1.0.0"
#define PROJECT_DESCRIPTION  "TLS Client"
#define PROJECT_VER_MAJOR "1"
#define PROJECT_VER_MINOR "0"
#define PROJECT_VER_PATCH "0"

#endif // PROJECT_VERSION_H
